### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by Belarussianin** [slavableat/TRITPO_LAB2#1]
Хоть приложение и анонимное, во избежание спама отзывами и других ситуаций, стоило бы добавить к отзыву имя оставившего, что не даст оставлять под одной книгой несколько отзывов от одного читателя.
Не пояснен формат для скачивания файлов.
Опечатка в содержании.

**Comment by slavableat** [comment]
Изменения внес, спасибо за рекомендации
